[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/scores/*.musicxml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/data/songs/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
